language: node_js
node_js:
- node
script:
- npm run ci
notifications:
  slack:
    secure: gX4I/ZQZ5lWXElX6ZIeI/DbtvkW8hozG5YWDSLBS66iu5Vvy73O03mtR8rZVFm5YEM7PRAAPTO9Y9TVMCz1Zul+dat9d7eF/rRhMzssoePAGFuAQwrY3Tt+Acmasnxv4msiT+cB4BkoRQYa9zsEXZmIGnQIwJ5Rvyo7TvJq5HapNTVhbd32hPrkZLK0yknlxPE9HbZV2vL23cKFSaLhJhWYFONzjx3W5SH9g+VBLnxNXcIVyPHSiDnS7zhvmuQ+/Mxc2mkCMIpIH5tysF8UCEzs/SN2hVVopExpLj7hG9j6gEv80nwzI7tvSzmQq3o573+hwI+msFei/2B2T9I4qqEuxbpbZpZv16toJ1tDF7v1rw8Ih5T4bWaEG+OO+DPQA0QYZIvw/COvoa53QAcLW3iWICBgRA24ofU1kYbZuhCvcAWOABDyNDZn9S2agJmxICdMd8/WRoqBiXj7SswOA1csbn8OXeyjGJo2y9PDMGCLOASWCT0BeJ3Qyz5LLNSfETY0+iUURbO92xs3G2BLhZGIDIgp/ma4g4tWX9baBPLCKb+KwaltHQVF0+EmL/oTl0NOb+CSGVoO1zngpUEfMtPqHghLK1XEnbyF9jWFI00hyW5BpJO+2ziSci0BzGOWvKqXkcDrpDN0m+oG09Zi+LLUiJNWT+oDwlO0dlW9n5LE=
